# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='birthdate',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='real_name',
            field=models.CharField(default='未命名', max_length=100),
        ),
    ]
