# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20170227_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='history_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='useable_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
