# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20170227_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='useable_points',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usable_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='history_points',
            field=models.IntegerField(default=0),
        ),
    ]
