# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_auto_20170227_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='無標題', max_length=100)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
