# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('remain', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.UserProfile')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.ItemList')),
            ],
        ),
        migrations.AlterField(
            model_name='story',
            name='topic',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
