# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20170227_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='opened_story',
            field=models.CharField(default='', max_length=100),
        ),
    ]
