# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-27 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_userprofile_opened_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
