# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-28 01:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_story_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='uid',
        ),
    ]
