# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-28 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0010_auto_20170228_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlist',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
