# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-02-28 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_itemlist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bought_items',
            field=models.CharField(default='', max_length=100),
        ),
    ]
