# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-01 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_userprofile_bought_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='topic',
            new_name='title',
        ),
    ]
