# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-01 09:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20170301_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingrecord',
            name='number',
        ),
    ]
