# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-07 05:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0014_remove_shoppingrecord_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.IntegerField(default=0)),
                ('item_quantity', models.IntegerField(default=0)),
                ('bought_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRcodeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_content', models.SlugField(max_length=40, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_content', models.SlugField(max_length=40, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QRcodeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('last_read', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoppingrecord',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='shoppingrecord',
            name='item',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='bought_items',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='history_points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='opened_story',
        ),
        migrations.DeleteModel(
            name='ShoppingRecord',
        ),
        migrations.AddField(
            model_name='qrcodestatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.UserProfile'),
        ),
        migrations.AddField(
            model_name='qrcoderecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.UserProfile'),
        ),
        migrations.AddField(
            model_name='boughtitems',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.UserProfile'),
        ),
    ]
