# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-07 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0015_auto_20170307_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.IntegerField(default=0)),
                ('bought_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.UserProfile')),
            ],
        ),
        migrations.RemoveField(
            model_name='boughtitems',
            name='bought_time',
        ),
    ]
