# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-08 07:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0016_auto_20170308_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcoderecord',
            name='code_content',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='qrcodestatus',
            name='last_read',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 8, 15, 6, 41, 356924)),
        ),
    ]
