# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-08 10:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0017_auto_20170308_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcoderecord',
            name='points_got',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='qrcodestatus',
            name='last_read',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 8, 18, 42, 16, 850192)),
        ),
    ]
