# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-09 07:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0019_auto_20170308_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodestatus',
            name='last_read',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 15, 39, 16, 65220)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.SlugField(max_length=20),
        ),
    ]
