# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-09 07:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0020_auto_20170309_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='未命名', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='qrcodestatus',
            name='last_read',
            field=models.DateTimeField(default=datetime.datetime(2017, 3, 9, 15, 50, 51, 940212)),
        ),
    ]
